import '../src/app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// Remove ClerkProvider import

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Akalın Tech Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
